import type { GameProvider } from '@/types/game.types';

export const GAME_PROVIDERS: GameProvider[] = [
  { id: '1', name: 'Asia Gaming', slug: 'asia-gaming', logo: '', gamesCount: 45, isActive: true },
  { id: '2', name: 'BetGames', slug: 'betgames', logo: '', gamesCount: 32, isActive: true },
  { id: '3', name: 'Betsoft', slug: 'betsoft', logo: '', gamesCount: 120, isActive: true },
  { id: '4', name: 'Evolution Gaming', slug: 'evolution-gaming', logo: '', gamesCount: 200, isActive: true },
  { id: '5', name: 'Evoplay Entertainment', slug: 'evoplay', logo: '', gamesCount: 85, isActive: true },
  { id: '6', name: 'Ezugi', slug: 'ezugi', logo: '', gamesCount: 55, isActive: true },
  { id: '7', name: 'Gamzix', slug: 'gamzix', logo: '', gamesCount: 40, isActive: true },
  { id: '8', name: 'JDB Gaming', slug: 'jdb-gaming', logo: '', gamesCount: 60, isActive: true },
  { id: '9', name: 'Jili', slug: 'jili', logo: '', gamesCount: 90, isActive: true },
  { id: '10', name: 'KINGMAKER', slug: 'kingmaker', logo: '', gamesCount: 35, isActive: true },
  { id: '11', name: 'Kingmidas Gaming', slug: 'kingmidas-gaming', logo: '', gamesCount: 25, isActive: true },
  { id: '12', name: 'Mac88', slug: 'mac88', logo: '', gamesCount: 30, isActive: true },
  { id: '13', name: 'Playtech', slug: 'playtech', logo: '', gamesCount: 150, isActive: true },
  { id: '14', name: 'Royal Gaming', slug: 'royal-gaming', logo: '', gamesCount: 45, isActive: true },
  { id: '15', name: 'SmartSoft Gaming', slug: 'smartsoft-gaming', logo: '', gamesCount: 20, isActive: true },
  { id: '16', name: 'Spribe', slug: 'spribe', logo: '', gamesCount: 15, isActive: true },
  { id: '17', name: 'Turbo Games', slug: 'turbo-games', logo: '', gamesCount: 18, isActive: true },
  { id: '18', name: 'Vivo Gaming', slug: 'vivo-gaming', logo: '', gamesCount: 50, isActive: true },
  { id: '19', name: 'Winfinity', slug: 'winfinity', logo: '', gamesCount: 22, isActive: true },
];

export const PROVIDER_ICONS: Record<string, string> = {
  'asia-gaming': '🎴',
  'betgames': '🎲',
  'betsoft': '🎰',
  'evolution-gaming': '🌀',
  'evoplay': '🎭',
  'ezugi': '🦊',
  'gamzix': '🌙',
  'jdb-gaming': '🀄',
  'jili': '🎪',
  'kingmaker': '👑',
  'kingmidas-gaming': '🏛️',
  'mac88': '🎯',
  'playtech': '🎮',
  'royal-gaming': '♛',
  'smartsoft-gaming': '🧠',
  'spribe': '🚀',
  'turbo-games': '⚡',
  'vivo-gaming': '📺',
  'winfinity': '♾️',
};
